# Copyright 2026 Amiasys Corporation and/or its affiliates. All rights reserved.

services:
  asnsn:
    image: registry.amiasys.com/asnsn:26.2.1
    ports:
      - "50052:52767"
    volumes:
      - ./cert/:/asn/cert
      - ./config/:/etc/asn/servicenode/config
      - ./service-config/:/etc/asn/servicenode/config
      - ./log/:/var/log/asn/servicenode
      - ./services:/usr/local/asn/servicenode/services
