// Copyright 2026 Amiasys Corporation and/or its affiliates. All rights reserved.

syntax = "proto3";

option go_package = "./;proto";

package asn_local;

service Controller {
  rpc ListServices    (Empty)             returns (stream ServiceRes);
  rpc StartService    (ServiceReq)        returns (Empty);
  rpc StopService     (ServiceReq)        returns (Empty);
  rpc RestartService  (ServiceReq)        returns (Empty);
  rpc ApplyServiceOps (Ops)               returns (OpsRes);
  rpc AddConfigOps    (ConfigOpsReq)      returns (ConfigOpsRes);
  rpc UpdateConfigOp  (UpdateConfigOpReq) returns (ConfigOpsRes);
  rpc DeleteConfigOps (ConfigOpsReq)      returns (ConfigOpsRes);
}

message Empty{}

message ServiceReq {
  string name = 1;
  string version = 2;
  string config = 3;
}

message ServiceRes {
  string name = 1;
  string version = 2;
  int32  state = 3;
}

message Ops {
  string name = 1;
  string command = 2;
  string params = 3;
}

message OpsRes {
  string response = 1;
}

message ConfigOpsReq {
  string service_name = 1;
  repeated string config_params = 2;
}

message UpdateConfigOpReq {
  string service_name = 1;
  string old_param = 2;
  string new_param = 3;
}

message ConfigOpsRes {
  string response = 1;
}
