// Copyright 2026 Amiasys Corporation and/or its affiliates. All rights reserved.

syntax = "proto3";

option go_package = "./;proto";

package asn_local;

service Controller {
  rpc ListServices(Empty)         returns (stream ServiceRes) {}
  rpc StartService(ServiceReq)    returns (Empty) {}
  rpc StopService(ServiceReq)     returns (Empty) {}
  rpc RestartService(ServiceReq)  returns (Empty) {}
  rpc ApplyServiceOps(Ops)        returns (OpsRes){}
}

message Empty{}

message ServiceReq {
  string name = 1;
  string version = 2;
  string config = 3;
}

message ServiceRes {
  string name = 1;
  string version = 2;
}

message Ops {
  string name = 1;
  string command = 2;
  string params = 3;
}

message OpsRes {
  string response = 1;
}
